# AQD (Adaptive Query Dispatching) Configuration
# Based on the AQD research paper implementation

# Database Configuration
database:
  postgresql:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    database: "aqd_test"
    connection_pool_size: 10
    
  # pg_duckdb extension settings
  pg_duckdb:
    enable_extension: true
    memory_limit: "2GB"
    thread_count: 4

# Routing Configuration
routing:
  # Cost-threshold routing parameters
  cost_threshold:
    oltp_threshold: 1000.0    # Queries below this cost route to PostgreSQL
    olap_threshold: 5000.0    # Queries above this cost route to DuckDB
    enable_adaptive_threshold: false
    
  # ML-based routing parameters  
  ml_routing:
    model_type: "lightgbm"
    model_path: "models/aqd_lightgbm_model.pkl"
    feature_count: 32         # Reduced from 142 raw features via SHAP analysis
    enable_online_learning: false
    confidence_threshold: 0.7
    
  # Advanced AQD features (future implementation)
  advanced:
    enable_thompson_sampling: false
    enable_mahalanobis_regulation: false
    resource_balance_weight: 0.3

# Training Configuration
training:
  # Data collection parameters
  data_collection:
    dual_execution: true
    max_training_samples: 10000
    sample_timeout: 30.0      # seconds
    enable_query_caching: true
    
  # LightGBM training parameters (from AQD paper)
  lightgbm:
    objective: "binary"
    metric: "binary_logloss"  
    boosting_type: "gbdt"
    num_leaves: 31
    learning_rate: 0.1
    feature_fraction: 0.8
    bagging_fraction: 0.8
    bagging_freq: 5
    num_boost_round: 100
    early_stopping_rounds: 10
    
    # Taylor-weighted boosting (AQD innovation)
    enable_cost_weighting: true
    weight_factor: 1.5
    
  # Feature engineering
  features:
    enable_feature_selection: true
    selection_method: "shap"  # SHAP-based feature importance
    target_feature_count: 32
    enable_feature_scaling: true

# Evaluation Configuration  
evaluation:
  # Benchmark parameters
  benchmark:
    query_timeout: 60.0       # seconds
    max_concurrent_queries: 100
    concurrency_levels: [1, 10, 50, 100]
    warmup_queries: 10
    
  # Query workload distribution
  workload:
    oltp_percentage: 40       # 40% OLTP queries
    olap_percentage: 40       # 40% OLAP queries  
    mixed_percentage: 20      # 20% mixed queries
    
  # Performance metrics
  metrics:
    measure_latency: true
    measure_throughput: true
    measure_accuracy: true
    measure_resource_usage: false  # Requires system monitoring
    
  # Result output
  output:
    save_detailed_results: true
    generate_visualizations: true
    export_format: ["json", "csv"]

# Logging Configuration
logging:
  level: "INFO"
  enable_query_logging: true
  enable_routing_decisions: true
  enable_performance_metrics: true
  log_file: "logs/aqd_system.log"
  max_log_size: "100MB"
  backup_count: 5

# System Configuration
system:
  # Resource limits
  resources:
    max_memory_usage: "4GB"
    max_cpu_percentage: 80.0
    enable_resource_monitoring: false
    
  # Performance tuning
  performance:
    enable_query_plan_caching: true
    enable_result_caching: false
    cache_size_limit: "1GB"
    
  # Fault tolerance
  fault_tolerance:
    enable_fallback_routing: true
    fallback_engine: "postgresql"  # Default to PostgreSQL on errors
    max_retry_attempts: 3
    retry_delay: 1.0            # seconds

# Experimental Features (for research)
experimental:
  # Online learning and adaptation
  online_learning:
    enable: false
    update_frequency: 100       # queries
    learning_rate_decay: 0.95
    
  # A/B testing framework
  ab_testing:
    enable: false
    test_ratio: 0.1            # 10% of queries for testing
    
  # Advanced routing algorithms
  advanced_routing:
    enable_bandit_algorithms: false
    enable_reinforcement_learning: false